package com.example.appiic;

import androidx.annotation.NonNull;
import androidx.appcompat.app.AppCompatActivity;

import android.content.Intent;
import android.media.MediaPlayer;
import android.os.Bundle;
import android.view.View;
import android.widget.AdapterView;
import android.widget.ArrayAdapter;
import android.widget.Button;
import android.widget.EditText;
import android.widget.Spinner;
import android.widget.Toast;

import com.google.android.gms.tasks.OnCompleteListener;
import com.google.android.gms.tasks.Task;
import com.google.firebase.auth.AuthResult;
import com.google.firebase.auth.FirebaseAuth;
import com.google.firebase.database.DatabaseReference;
import com.google.firebase.database.FirebaseDatabase;

import java.util.ArrayList;
import java.util.List;

public class Facultysignup extends AppCompatActivity {

    private Button button7;
    private EditText editText3;
    private EditText editText9;
    private EditText editText10;
    private EditText editText11;
    private EditText editText12;
    private FirebaseAuth fAuth;
    private Spinner spinner4;
    private String dept;
    FirebaseDatabase firebaseDatabases;
    DatabaseReference databaseReferences;
    String email,password;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_facultysignup);

        button7=findViewById(R.id.button7);
        editText10=findViewById(R.id.editText10);
        editText3=findViewById(R.id.editText3);
        editText9=findViewById(R.id.editText9);
        editText11=findViewById(R.id.editText11);
        editText12=findViewById(R.id.editText12);
        final MediaPlayer mediaPlayer1=MediaPlayer.create(this,R.raw.buttonsound2);

         spinner4=findViewById(R.id.spinner4);

         List<String> categories=new ArrayList<>();
         categories.add(0,"Department");
         categories.add("CSE");
         categories.add("AUTO");
         categories.add("MECH");
         categories.add("CIVIL");
         categories.add("EEE");
         categories.add("EIE");
         categories.add("ECE");
         categories.add("IT");
         categories.add("CHEMISTRY");
         categories.add("PHYSICS");
         categories.add("MATHEMATICS");

         ArrayAdapter<String> dataAdapter;
         dataAdapter=new ArrayAdapter(this,android.R.layout.simple_spinner_item,categories);

         dataAdapter.setDropDownViewResource(android.R.layout.simple_spinner_dropdown_item);

         spinner4.setAdapter(dataAdapter);
         spinner4.setOnItemSelectedListener(new AdapterView.OnItemSelectedListener() {
             @Override
             public void onItemSelected(AdapterView<?> parent, View view, int position, long id) {

                 if(parent.getItemAtPosition(position).equals("Department")){
                     //do nothing
                    dept=null;
                 }
                 else{
                     //on selecting sppiner item
                     String item=parent.getItemAtPosition(position).toString();
                     //show spiner item
                     Toast.makeText(parent.getContext(),"selected:"+item,Toast.LENGTH_SHORT).show();
                     //anything u want do here
                     dept=spinner4.getSelectedItem().toString();


                 }
             }

             @Override
             public void onNothingSelected(AdapterView<?> parent) {
                 //TODO AUTOGENERATED METHOD DO HERE

             }
         });

        fAuth=FirebaseAuth.getInstance();

        /*final ArrayAdapter<String> adapter=new ArrayAdapter<>(
                this,
                R.layout.custom_spinner,
                getResources().getStringArray(R.array.Department)
        );

        adapter.setDropDownViewResource(R.layout.custom_spinner_dropdown);
        spinner4.setAdapter(adapter);*/

        databaseReferences=FirebaseDatabase.getInstance().getReference("Faculty");

        button7.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {

                final String usernames = editText3.getText().toString();
                final String IDNo = editText9.getText().toString();
                final String emaili = editText10.getText().toString();
                final String mobno = editText12.getText().toString();


                email = editText10.getText().toString();
                password = editText11.getText().toString();

                mediaPlayer1.start();

                if (editText3.length() == 0) {
                    editText3.setError("Enter Username!");
                } else if (editText9.length() == 0) {
                    editText9.setError("Enter ID-no!");
                } else if (editText10.length() == 0) {
                    editText10.setError("Enter Mail-id!");
                } else if (editText11.length() == 0) {
                    editText11.setError("Enter Password!");
                } else if (editText12.length() == 0 || editText12.length() != 10) {
                    editText12.setError("Enter Mobile-No!");
                } else if(dept==null){
                    Toast.makeText(Facultysignup.this, " select department",
                            Toast.LENGTH_SHORT).show();
                }
                    else{
                    fAuth.createUserWithEmailAndPassword(email, password)
                            .addOnCompleteListener(Facultysignup.this, new OnCompleteListener<AuthResult>() {
                                @Override
                                public void onComplete(@NonNull Task<AuthResult> task) {

                                    if (task.isSuccessful()) {

                                        final Faculty info = new Faculty(
                                                usernames,
                                                IDNo,
                                                emaili,
                                                mobno,
                                                dept
                                        );

                                        FirebaseDatabase.getInstance().getReference("Faculty")
                                                .child(FirebaseAuth.getInstance().getCurrentUser().getUid())
                                                .setValue(info).addOnCompleteListener(new OnCompleteListener<Void>() {
                                            @Override
                                            public void onComplete(@NonNull Task<Void> task) {
                                                Toast.makeText(Facultysignup.this, "Authentication success,",
                                                        Toast.LENGTH_SHORT).show();
                                                Intent intent = new Intent(Facultysignup.this, faculty_profile.class);
                                                startActivity(intent);
                                                finish();
                                            }
                                        });

                                    } else {
                                        Toast.makeText(Facultysignup.this, "Authentication failed.",
                                                Toast.LENGTH_SHORT).show();
                                    }
                                }
                            });
                }
            }
        });
    }
    @Override
    public void onBackPressed(){
        super.onBackPressed();
        Intent intent=new Intent(Facultysignup.this,Register.class);
        startActivity(intent);
    }
}
